const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.custom,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Plugins.NinePatch,
		C3.Behaviors.Follow,
		C3.Behaviors.Bullet,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.SetEnabled,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Behaviors.Follow.Acts.SetMaxDelay,
		C3.Behaviors.Follow.Exps.Delay,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Follow.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Exps.viewportleft,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.NinePatch.Cnds.CompareY,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareChildCount,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{Mouse: 0},
	{Audio: 0},
	{a: 0},
	{d: 0},
	{TArea: 0},
	{TPin: 0},
	{frutillas: 0},
	{wood: 0},
	{stone: 0},
	{orange: 0},
	{carbon: 0},
	{nRescue: 0},
	{girasol: 0},
	{carrot: 0},
	{calabaza: 0},
	{player: 0},
	{TPin2: 0},
	{action: 0},
	{axe: 0},
	{pico: 0},
	{pala: 0},
	{semillas_girasol: 0},
	{semillas_carrot: 0},
	{semillas_calabaza: 0},
	{energyT: 0},
	{energy: 0},
	{resourceID: 0},
	{nTuto: 0},
	{"8Direction": 0},
	{Custom: 0},
	{Tween: 0},
	{posY: 0},
	{player_spr: 0},
	{Solid: 0},
	{Tilemap: 0},
	{ScrollTo: 0},
	{camera: 0},
	{bridge: 0},
	{wall: 0},
	{healthI: 0},
	{health: 0},
	{timerI: 0},
	{timer: 0},
	{state: 0},
	{resource: 0},
	{barID: 0},
	{puederegar: 0},
	{icon: 0},
	{iconcreated: 0},
	{bush_frutilla: 0},
	{bgBar: 0},
	{startW: 0},
	{bar: 0},
	{ui_items: 0},
	{name: 0},
	{txtUI: 0},
	{water: 0},
	{inventory: 0},
	{lock: 0},
	{txtUI2: 0},
	{tree_wood: 0},
	{regador: 0},
	{pozo: 0},
	{bush_frutilla2: 0},
	{horno: 0},
	{nIndex: 0},
	{Follow: 0},
	{player_blue: 0},
	{Bullet: 0},
	{boat: 0},
	{Tilemap2: 0},
	{bolsa_girasol: 0},
	{nodo_girasol: 0},
	{sign_girasol: 0},
	{nodo_carrot: 0},
	{sign_carrot: 0},
	{bolsa_carrot: 0},
	{sign_calabaza: 0},
	{bolsa_calabaza: 0},
	{nodo_calabaza: 0},
	{Anchor: 0},
	{bgUIBottom: 0},
	{tool: 0},
	{uiIconTool: 0},
	{Sine: 0},
	{icon_indication: 0},
	{bgUIAnchor: 0},
	{objects_to_collect: 0},
	{ui_item_action: 0},
	{txtUI3: 0},
	{cloud: 0},
	{black: 0},
	{masc: 0},
	{"9patch": 0},
	{horno_pop_up: 0},
	{tilemap_house: 0},
	{bed: 0},
	{house_deco: 0},
	{bgPlayerUI: 0},
	{bgBarEnergy: 0},
	{barEnergy: 0},
	{show: 0},
	{roof: 0},
	{masc_roof: 0},
	{no_energy: 0},
	{alert: 0},
	{win: 0},
	{btnNext: 0},
	{transition: 0},
	{tap_to_play: 0},
	{z: 0},
	{deco: 0},
	{Fade: 0},
	{Sine2: 0},
	{hand: 0},
	{tutorial: 0},
	{arrow: 0},
	{SortZ: 0},
	{Resources: 0},
	{Buttons: 0},
	{showThumbstick: 0},
	{dist: 0},
	{ENDGAME: 0},
	{GAMENAME: 0},
	{moving_angle: 0},
	{resourceX: 0},
	{resourceY: 0},
	{regar: 0},
	{runaction: 0},
	{tpinUID: 0},
	{cant: 0},
	{substract: 0},
	{mag: 0},
	{dur: 0},
	{newangle: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newLayer: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	TArea: class extends self.ISpriteInstance {},
	TPin: class extends self.ISpriteInstance {},
	TPin2: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	player_spr: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	camera: class extends self.ISpriteInstance {},
	bridge: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	bush_frutilla: class extends self.ISpriteInstance {},
	bgBar: class extends self.ISpriteInstance {},
	bar: class extends self.ISpriteInstance {},
	ui_items: class extends self.ISpriteInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	inventory: class extends self.ISpriteInstance {},
	lock: class extends self.I9PatchInstance {},
	txtUI2: class extends self.ISpriteFontInstance {},
	tree_wood: class extends self.ISpriteInstance {},
	regador: class extends self.ISpriteInstance {},
	pozo: class extends self.ISpriteInstance {},
	axe: class extends self.ISpriteInstance {},
	pico: class extends self.ISpriteInstance {},
	stone: class extends self.ISpriteInstance {},
	bush_frutilla2: class extends self.ISpriteInstance {},
	pala: class extends self.ISpriteInstance {},
	horno: class extends self.ISpriteInstance {},
	player_blue: class extends self.ISpriteInstance {},
	boat: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	bolsa_girasol: class extends self.ISpriteInstance {},
	nodo_girasol: class extends self.ISpriteInstance {},
	sign_girasol: class extends self.ISpriteInstance {},
	nodo_carrot: class extends self.ISpriteInstance {},
	sign_carrot: class extends self.ISpriteInstance {},
	bolsa_carrot: class extends self.ISpriteInstance {},
	sign_calabaza: class extends self.ISpriteInstance {},
	bolsa_calabaza: class extends self.ISpriteInstance {},
	nodo_calabaza: class extends self.ISpriteInstance {},
	bgUIBottom: class extends self.I9PatchInstance {},
	uiIconTool: class extends self.ISpriteInstance {},
	icon_indication: class extends self.ISpriteInstance {},
	bgUIAnchor: class extends self.ISpriteInstance {},
	objects_to_collect: class extends self.ISpriteInstance {},
	ui_item_action: class extends self.ISpriteInstance {},
	txtUI3: class extends self.ISpriteFontInstance {},
	cloud: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	masc: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	horno_pop_up: class extends self.ISpriteInstance {},
	tilemap_house: class extends self.ITilemapInstance {},
	bed: class extends self.ISpriteInstance {},
	house_deco: class extends self.ISpriteInstance {},
	bgPlayerUI: class extends self.ISpriteInstance {},
	bgBarEnergy: class extends self.I9PatchInstance {},
	barEnergy: class extends self.I9PatchInstance {},
	roof: class extends self.I9PatchInstance {},
	masc_roof: class extends self.ISpriteInstance {},
	no_energy: class extends self.ISpriteInstance {},
	alert: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	btnNext: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	tap_to_play: class extends self.ISpriteInstance {},
	z: class extends self.ISpriteInstance {},
	deco: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	SortZ: class extends self.ISpriteInstance {},
	Resources: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}